# Generated by Django 5.1.3 on 2024-11-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(),
        ),
    ]
